print("Restaurant Data")
print("Arizona restaurant data retrieved from: https://www.yelp.com/search?find_desc=&find_loc=Arizona")
print("Connecticut restarant data retrieved from: https://www.yelp.com/search?find_desc=Restaurants&find_loc=Connecticut%2C%20CT&ed_attrs=PlatformPickup%2CPlatformDelivery)
print("Utah restaurant data retrieved from: https://www.yelp.com/search?find_desc=salt%20lake&find_loc=utah")
print("Alaska restaurant data retrieved from: https://www.yelp.com/search?find_desc=anchorage&find_loc=alaska")
